import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The docs sidebar is generated from the folder structure under docs/, ordered by
// each page's `sidebar_position` frontmatter and each folder's `_category_.json`.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
